apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: PluginLove
spec:
  enabled: true
  requires: ">=2.23.0"
  author:
    name: Monster
    website: https://github.com/dengchuanfu
  logo: logo.svg
  homepage: https://github.com/dengchuanfu/halo-plugin-love
  repo: https://github.com/dengchuanfu/halo-plugin-love
  issues: https://github.com/dengchuanfu/halo-plugin-love/issues
  displayName: "情侣主页"
  description: "为 Halo 提供全屏情侣纪念主页，支持自定义壁纸、头像、昵称与相恋时长计时。"
  settingName: love-page-settings
  configMapName: love-page-config
  license:
    - name: "MIT"
